name: Publish Preview

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the action'
        required: false
        default: 'Pre-Release'
      private:
        description: 'Whether to publish to the private feed'
        required: false
        default: 'true'
      public:
        description: 'Whether to publish to the public NuGet feed'
        required: false
        default: 'false'

env:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.10
      with:
        useConfigFile: true

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: >
        dotnet build
        --configuration $buildConfiguration
        --no-restore

    - name: Test
      run: >
        dotnet test
        --configuration $buildConfiguration
        --no-build
        --verbosity normal
        --collect "Code coverage"

    - name: Pack
      run: >
        dotnet pack
        --configuration $buildConfiguration
        --no-build
        --verbosity Detailed
        --output $GITHUB_WORKSPACE/drop
        -p:PackageVersion=$GITVERSION_NUGETVERSION

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/drop/*
        name: drop

  PrivateFeed:
    runs-on: ubuntu-latest
    needs: Build
    if: eq(github.event.inputs.private, 'true')

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.workspace }}/drop

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        source-url: ${{ secrets.PRIVATE_FEED_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PRIVATE_FEED_API_KEY }}

    - name: Publish to NuGet.org
      # if: startsWith(github.ref, 'refs/tags/')
      run: >
        dotnet nuget push "$GITHUB_WORKSPACE/drop/*"
        -k ${{ secrets.PRIVATE_FEED_API_KEY }}
        --skip-duplicate

  PublicFeed:
    runs-on: ubuntu-latest
    needs: Build
    if: eq(github.event.inputs.public, 'true')

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.workspace }}/drop

    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Publish to NuGet.org
      # if: startsWith(github.ref, 'refs/tags/')
      run: >
        dotnet nuget push "$GITHUB_WORKSPACE/drop/*"
        -k ${{ secrets.NUGET_API_KEY }}
        --skip-duplicate
